name: ⭐ Feature request
description: Create a detailed request for a new feature.
title: 'feat: '
labels: ['feature']
body:
  - type: markdown
    attributes:
      value: |
        # Morphe Patches feature request

        Before creating a new feature request, please keep the following in mind:

        - We are currently only accept feature requests for YouTube and YT Music patches.
        - **Do not submit a duplicate feature request**: Search for existing feature requests, including closed issues, [here](https://github.com/MorpheApp/morphe-patches/issues?q=label%3A%22Feature+request%22).
  - type: textarea
    attributes:
      label: Feature description
      description: |
        - Describe your feature in detail
  - type: textarea
    attributes:
      label: Motivation
      description: | 
        A strong motivation is necessary for a feature request to be considered.
        
        - Why should this feature be implemented? 
        - What is the explicit use case?
        - What are the benefits?
        - What makes this feature important?
    validations:
      required: true
  - type: checkboxes
    id: acknowledgements
    attributes:
      label: Acknowledgements
      description: Your feature request will be closed if you don't follow the checklist below.
      options:
        - label: I have checked all open and closed feature requests and this is not a duplicate
          required: true
        - label: This is a feature request for YouTube or YT Music
          required: true
